### ISSUE TITLE
REST API key usage

### ISSUE THREAD

**Issue by olaf7** [scm-manager/scm-redmine-plugin#10]
In SCM Manager 1.x the plugin requires a redmine REST API key bound to a user.
This seems not to be available in SCM Manager 2.x

* The authentication method is not documented security wise: is desirable to have a scm-redmine user or should a project linked per project manager or ... ? (best solution seems to me. This is (not) the case  for both SCM Manager 1.x and 2.x
* The REST API key is no longer supported in SCM 2.x
* Settings of the plugin are not migrated from 1.x to 2.x
* The project URL is empty. Why not template this: http(s)://<redmineserver>/projects/<project>  based on generic plugin settings, but manually adjustable per project
* a test connect option would be a nice addition

**Comment by pfeuffer** [comment]
SCM-Manager used the SCM password of the current user to connect to Redmine. We removed this behaviour, because with v2 we do no longer have a session where we could keep the password and we wanted to have the ability for other authentication mechanisims. So in v2 you have to specify a dedicated Redmine user for the connection (either in the global or the repository specific redmine configuration).

I have to admit that I don't know what you mean with the REST API key, because as far as I know we never used keys for Redmine in SCM-Manager (only username/password). Can you elaborate on that?

As for the mussing migration: We had a bug in SCM-Manager. You reported this [here](https://github.com/scm-manager/scm-redmine-plugin/issues/6) and we think we fixed this with [this fix](https://github.com/scm-manager/scm-manager/issues/1237) in release 2.3.0. Do you still have this issue?

As for your suggestions for improvements, can you please create two separate issues, so that we can track them seperatedly?

Thank you for your support!

**Comment by olaf7** [comment]
Migration was successful as in : no errors. But it also left the redmine config per project empty. Fine with limited projects, but otherwise a pita. Fine by me though, I only have 20 projects or so.

In my memory (my current 1.6 SCM no longer works) the plugin needed the API key. I had no recollection for the need of user/password config. Just noticed the docs for 1.x and 2.x are not that different ;-) https://www.scm-manager.org/docs/1.x/en/redmine-plugin/ 

I will file separate issues later.
